# Generated by Django 6.0.1 on 2026-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=80, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('is_apply', models.BooleanField(default=False)),
                ('apply_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
